import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import "reflect-metadata";
import NextAuthSessionProvider from "@/components/NextAuthSessionProvider";
import { auth } from "@/auth";
import ReactQueryClientProvider from "@/components/ReactQueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <NextAuthSessionProvider session={session}>
        <ReactQueryClientProvider>
          <body>{children}</body>
        </ReactQueryClientProvider>
      </NextAuthSessionProvider>
    </html>
  );
}
